Repository rtrlib/rtrlib, pull requests merged in 2018-10, with the labels that each got.

#179 Fix Debian packaging.
  debian/changelog
  debian/control
  debian/copyright
  debian/librtr-dbg.lintian-overrides
  debian/librtr-dev.lintian-overrides
  debian/librtr-doc.lintian-overrides
  debian/librtr0.lintian-overrides
  debian/rtr-tools-dbg.lintian-overrides
  debian/rtr-tools.lintian-overrides
  debian/source/format
Labels: type:enhancement

#181 update to 0.6.0
  CHANGELOG
  CMakeLists.txt
  debian/changelog
  debian/copyright
Labels: priority:high, type:enhancement

#187 README: replace IETF draft by RFC 8210, add C11 compiler requirement
  README
Labels: type:documentation
