Repository rtrlib/rtrlib, pull requests merged in 2018-11, with the labels that each got.

#188 rtr_mgr: wrap tommy_list in rtr_mgr_config in a struct
  rtrlib/rtr_mgr.c
  rtrlib/rtr_mgr.h
  rtrlib/rtr_mgr_private.h
  rtrlib/spki/hashtable/hashtable_forward.h
  tests/test_dynamic_groups.c
Labels: priority:medium, type:enhancement

#192 CMake: fix library installation path
  CMakeLists.txt
Labels: priority:medium, type:enhancement

#197 cmake: fix library installation path (again)
  CMakeLists.txt
Labels: priority:high

#198 tests: add connect timeout to test_dynamic_groups
  tests/test_dynamic_groups.c
Labels: priority:high, type:enhancement
