Repository rtrlib/rtrlib, pull requests merged in 2019-02, with the labels that each got.

#210 redhat: Fix tar command to move options before file
  redhat/SPECS/librtr.spec
Labels: priority:low, type:enhancement

#216 add Github templates for issues and PRs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority:low, type:enhancement

#220 Github templates: fix inconsistent layout of captions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: priority:low, type:bug

#215 rtrlib/rtr_mgr: fix check ensuring uniqueness of group preferences
  rtrlib/rtr_mgr.c
Labels: priority:medium, type:bug

#214 rtrlib/rtr: fix race condition in rtr_stop
  rtrlib/rtr/packets.c
  rtrlib/rtr/rtr.c
Labels: priority:high, type:bug
